# RuntimeError: mat1 and mat2 shapes cannot be multiplied (300x0 and 32x16128)
```python
Traceback (most recent call last):
  File "E:\source_code\annotation_of_yolov8_segmentpose\train_tomato_peduncle_seg_pose.py", line 19, in <module>
  File "E:\source_code\annotation_of_yolov8_segmentpose\train_tomato_peduncle_seg_pose.py", line 19, in <module>
    model.train(data=DATA_PATH, name=f'train_segmentposecoco_{args.model}', lr0=1e-4, epochs=200, batch=8, device='cpu')
  File "E:\source_code\annotation_of_yolov8_segmentpose\ultralytics\yolo\engine\model.py", line 376, in train
    self.trainer.train()
  File "E:\source_code\annotation_of_yolov8_segmentpose\ultralytics\yolo\engine\trainer.py", line 192, in train
    self._do_train(world_size)
  File "E:\source_code\annotation_of_yolov8_segmentpose\ultralytics\yolo\engine\trainer.py", line 372, in _do_train
    self.metrics, self.fitness = self.validate()
  File "E:\source_code\annotation_of_yolov8_segmentpose\ultralytics\yolo\engine\trainer.py", line 478, in validate
    metrics = self.validator(self)
  File "C:\Users\admin\.conda\envs\yolov8_seg_pose\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "E:\source_code\annotation_of_yolov8_segmentpose\ultralytics\yolo\engine\validator.py", line 173, in __call__
    self.update_metrics(preds, batch)
  File "E:\source_code\annotation_of_yolov8_segmentpose\ultralytics\yolo\v8\segment_pose\val.py", line 132, in update_metrics
    pred_masks = self.process(proto, mask_coeff_cols, pred[:, :4], shape=batch['img'][si].shape[1:])
  File "E:\source_code\annotation_of_yolov8_segmentpose\ultralytics\yolo\utils\ops.py", line 603, in process_mask
    masks = (masks_in @ protos.float().view(c, -1)).sigmoid().view(-1, mh, mw)  # CHW
RuntimeError: mat1 and mat2 shapes cannot be multiplied (300x0 and 32x16128)

```